name: Lint

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6 # https://github.com/actions/checkout/releases
      - name: Check workflow files
        uses: docker://rhysd/actionlint:1.6.27 # https://hub.docker.com/r/rhysd/actionlint/tags
        with:
          args: -color
